language: node_js
node_js:
    - 'lts/*'
    - 'node'
services: mongodb
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: OhDXzhmZGTBZdqgB0N4ihHpKixuvuNBP9Zd3PGW7tuXoGwqYDDhyOtpsTsgPV27VdblyKXbHwijxAJpZiZNaCRRRWHH5BFaImfVykqxBnKX3qrdepVm7MQ+hUweRdbxCnog0fTQs9ckUqrOJwyGd02TrUFaePslF4T0d3CZvw1M=
  app: hidden-depths-2780
  on:
    repo: deiga/Carpenter
    branch: dev
    node: node
